export const POSTS = [
	{
		_id: "1",
		text: "Let's build a fullstack WhatsApp clone with NEXT.JS 14 😍",
		img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRnnFf6DXcgRxe71BOQm1orHpnKjJloo9c2jg&s",
		user: {
			username: "johndoe",
			profileImg: "https://scontent.fdac24-5.fna.fbcdn.net/v/t39.30808-6/457801924_18465264949057705_2288315333087811111_n.jpg?_nc_cat=103&ccb=1-7&_nc_sid=127cfc&_nc_ohc=weODVxJiNwsQ7kNvgFvfz38&_nc_ht=scontent.fdac24-5.fna&_nc_gid=AlhqZ1FjejoHMkT-bDBDtzz&oh=00_AYAnnnmBviGuYzIy6tg5CDCIV4_wczSho23bMHGKAtdq_Q&oe=66E0DCDF",
			fullName: "John Doe",
		},
		comments: [
			{
				_id: "1",
				text: "Nice Tutorial",
				user: {
					username: "janedoe",
					profileImg: "https://scontent.fdac24-5.fna.fbcdn.net/v/t39.30808-6/457801924_18465264949057705_2288315333087811111_n.jpg?_nc_cat=103&ccb=1-7&_nc_sid=127cfc&_nc_ohc=weODVxJiNwsQ7kNvgFvfz38&_nc_ht=scontent.fdac24-5.fna&_nc_gid=AlhqZ1FjejoHMkT-bDBDtzz&oh=00_AYAnnnmBviGuYzIy6tg5CDCIV4_wczSho23bMHGKAtdq_Q&oe=66E0DCDF",
					fullName: "Jane Doe",
				},
			},
		],
		likes: ["6658s891", "6658s892", "6658s893", "6658s894"],
	},
	{
		_id: "2",
		text: "How you guys doing? 😊",
		user: {
			username: "johndoe",
			profileImg: "https://scontent.fdac24-5.fna.fbcdn.net/v/t39.30808-6/457801924_18465264949057705_2288315333087811111_n.jpg?_nc_cat=103&ccb=1-7&_nc_sid=127cfc&_nc_ohc=weODVxJiNwsQ7kNvgFvfz38&_nc_ht=scontent.fdac24-5.fna&_nc_gid=AlhqZ1FjejoHMkT-bDBDtzz&oh=00_AYAnnnmBviGuYzIy6tg5CDCIV4_wczSho23bMHGKAtdq_Q&oe=66E0DCDF",
			fullName: "John Doe",
		},
		comments: [
			{
				_id: "1",
				text: "Nice Tutorial",
				user: {
					username: "janedoe",
					profileImg: "https://scontent.fdac24-5.fna.fbcdn.net/v/t39.30808-6/457801924_18465264949057705_2288315333087811111_n.jpg?_nc_cat=103&ccb=1-7&_nc_sid=127cfc&_nc_ohc=weODVxJiNwsQ7kNvgFvfz38&_nc_ht=scontent.fdac24-5.fna&_nc_gid=AlhqZ1FjejoHMkT-bDBDtzz&oh=00_AYAnnnmBviGuYzIy6tg5CDCIV4_wczSho23bMHGKAtdq_Q&oe=66E0DCDF",
					fullName: "Jane Doe",
				},
			},
		],
		likes: ["6658s891", "6658s892", "6658s893", "6658s894"],
	},
	{
		_id: "3",
		text: "Astronaut in a room of drawers, generated by Midjourney. 🚀",
		img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRnnFf6DXcgRxe71BOQm1orHpnKjJloo9c2jg&s",
		user: {
			username: "johndoe",
			profileImg: "https://scontent.fdac24-5.fna.fbcdn.net/v/t39.30808-6/457801924_18465264949057705_2288315333087811111_n.jpg?_nc_cat=103&ccb=1-7&_nc_sid=127cfc&_nc_ohc=weODVxJiNwsQ7kNvgFvfz38&_nc_ht=scontent.fdac24-5.fna&_nc_gid=AlhqZ1FjejoHMkT-bDBDtzz&oh=00_AYAnnnmBviGuYzIy6tg5CDCIV4_wczSho23bMHGKAtdq_Q&oe=66E0DCDF",
			fullName: "John Doe",
		},
		comments: [],
		likes: ["6658s891", "6658s892", "6658s893", "6658s894", "6658s895", "6658s896"],
	},
	{
		_id: "4",
		text: "I'm learning GO this week. Any tips? 🤔",
		img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRnnFf6DXcgRxe71BOQm1orHpnKjJloo9c2jg&s",
		user: {
			username: "johndoe",
			profileImg: "https://scontent.fdac24-5.fna.fbcdn.net/v/t39.30808-6/457801924_18465264949057705_2288315333087811111_n.jpg?_nc_cat=103&ccb=1-7&_nc_sid=127cfc&_nc_ohc=weODVxJiNwsQ7kNvgFvfz38&_nc_ht=scontent.fdac24-5.fna&_nc_gid=AlhqZ1FjejoHMkT-bDBDtzz&oh=00_AYAnnnmBviGuYzIy6tg5CDCIV4_wczSho23bMHGKAtdq_Q&oe=66E0DCDF",
			fullName: "John Doe",
		},
		comments: [
			{
				_id: "1",
				text: "Nice Tutorial",
				user: {
					username: "janedoe",
					profileImg: "https://scontent.fdac24-5.fna.fbcdn.net/v/t39.30808-6/457801924_18465264949057705_2288315333087811111_n.jpg?_nc_cat=103&ccb=1-7&_nc_sid=127cfc&_nc_ohc=weODVxJiNwsQ7kNvgFvfz38&_nc_ht=scontent.fdac24-5.fna&_nc_gid=AlhqZ1FjejoHMkT-bDBDtzz&oh=00_AYAnnnmBviGuYzIy6tg5CDCIV4_wczSho23bMHGKAtdq_Q&oe=66E0DCDF",
					fullName: "Jane Doe",
				},
			},
		],
		likes: [
			"6658s891",
			"6658s892",
			"6658s893",
			"6658s894",
			"6658s895",
			"6658s896",
			"6658s897",
			"6658s898",
			"6658s899",
		],
	},
];

export const USERS_FOR_RIGHT_PANEL = [
	{
		_id: "1",
		fullName: "John Doe",
		username: "johndoe",
		profileImg: "https://scontent.fdac24-5.fna.fbcdn.net/v/t39.30808-6/457801924_18465264949057705_2288315333087811111_n.jpg?_nc_cat=103&ccb=1-7&_nc_sid=127cfc&_nc_ohc=weODVxJiNwsQ7kNvgFvfz38&_nc_ht=scontent.fdac24-5.fna&_nc_gid=AlhqZ1FjejoHMkT-bDBDtzz&oh=00_AYAnnnmBviGuYzIy6tg5CDCIV4_wczSho23bMHGKAtdq_Q&oe=66E0DCDF",
	},
	{
		_id: "2",
		fullName: "Jane Doe",
		username: "janedoe",
		profileImg: "https://scontent.fdac24-5.fna.fbcdn.net/v/t39.30808-6/457801924_18465264949057705_2288315333087811111_n.jpg?_nc_cat=103&ccb=1-7&_nc_sid=127cfc&_nc_ohc=weODVxJiNwsQ7kNvgFvfz38&_nc_ht=scontent.fdac24-5.fna&_nc_gid=AlhqZ1FjejoHMkT-bDBDtzz&oh=00_AYAnnnmBviGuYzIy6tg5CDCIV4_wczSho23bMHGKAtdq_Q&oe=66E0DCDF",
	},
	{
		_id: "3",
		fullName: "Bob Doe",
		username: "bobdoe",
		profileImg: "https://scontent.fdac24-5.fna.fbcdn.net/v/t39.30808-6/457801924_18465264949057705_2288315333087811111_n.jpg?_nc_cat=103&ccb=1-7&_nc_sid=127cfc&_nc_ohc=weODVxJiNwsQ7kNvgFvfz38&_nc_ht=scontent.fdac24-5.fna&_nc_gid=AlhqZ1FjejoHMkT-bDBDtzz&oh=00_AYAnnnmBviGuYzIy6tg5CDCIV4_wczSho23bMHGKAtdq_Q&oe=66E0DCDF",
	},
	{
		_id: "4",
		fullName: "Daisy Doe",
		username: "daisydoe",
		profileImg: "https://scontent.fdac24-5.fna.fbcdn.net/v/t39.30808-6/457801924_18465264949057705_2288315333087811111_n.jpg?_nc_cat=103&ccb=1-7&_nc_sid=127cfc&_nc_ohc=weODVxJiNwsQ7kNvgFvfz38&_nc_ht=scontent.fdac24-5.fna&_nc_gid=AlhqZ1FjejoHMkT-bDBDtzz&oh=00_AYAnnnmBviGuYzIy6tg5CDCIV4_wczSho23bMHGKAtdq_Q&oe=66E0DCDF",
	},
];